apiVersion: v1
kind: Namespace
metadata:
  name: FILLED_IN_BY_CI
  labels:
    sandboxId: FILLED_IN_BY_CI
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: FILLED_IN_BY_CI
  namespace: FILLED_IN_BY_CI
spec:
  interval: 5m0s
  url: https://github.com/biomage-org/iac
  ref:
    branch: FILLED_IN_BY_CI
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: FILLED_IN_BY_CI
  namespace: FILLED_IN_BY_CI
  labels:
    sandboxId: FILLED_IN_BY_CI
  annotations:
    filter.fluxcd.io/chart-image: FILLED_IN_BY_CI
spec:
  releaseName: FILLED_IN_BY_CI
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: FILLED_IN_BY_CI
        namespace: FILLED_IN_BY_CI
  values:
    # disable readiness probes as load balancer performs
    # its own health checks/cordoning
    readinessProbe:
      probeType: exec
      command: ["echo", "0"]
    loadBalancerHealthCheck:
      path: "/robots.txt"
      periodSeconds: 30
    livenessProbe:
      probeType: tcpSocket
    service:
      additionalHosts: FILLED_IN_BY_CI
  valuesFrom:
    - kind: ConfigMap
      name: account-config
      valuesKey: account-config.yaml
      optional: false
      # filled in by CI. do not modify.
